import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const webRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = resolve(webRoot, "..", "translations.py");
const outputPath = resolve(webRoot, "src", "generated", "translations.ts");
const locales = ["en", "vi", "ja"];

function parsePythonCatalog(source) {
  const catalogs = {};
  let activeLocale = null;

  for (const line of source.split(/\r?\n/u)) {
    const start = line.match(/^_(?:(?:REACT|PHASE5)_)?([A-Z]{2})(?:\s*:\s*[^=]+)?\s*=\s*\{$/u);
    if (start) {
      activeLocale = start[1].toLowerCase();
      catalogs[activeLocale] ??= {};
      continue;
    }
    if (activeLocale && line.trim() === "}") {
      activeLocale = null;
      continue;
    }
    if (!activeLocale) continue;

    const entries = line.matchAll(/"([^"\\]+)"\s*:\s*"((?:\\.|[^"\\])*)"\s*,/gu);
    for (const entry of entries) {
      const [, key, encodedValue] = entry;
      catalogs[activeLocale][key] = JSON.parse(`"${encodedValue}"`);
    }
  }

  for (const locale of locales) {
    if (!catalogs[locale] || Object.keys(catalogs[locale]).length === 0) {
      throw new Error(`Could not parse the ${locale} catalog from ${sourcePath}.`);
    }
  }
  const expected = Object.keys(catalogs.en).sort();
  for (const locale of locales.slice(1)) {
    const actual = Object.keys(catalogs[locale]).sort();
    if (expected.join("\n") !== actual.join("\n")) {
      throw new Error(`Translation key drift detected for ${locale}.`);
    }
  }
  return catalogs;
}

const source = await readFile(sourcePath, "utf8");
const translations = parsePythonCatalog(source);
const output = `/* This file is generated by web/scripts/generate-i18n.mjs. Do not edit it directly. */\n\nexport const supportedLocales = ["en", "vi", "ja"] as const;\nexport type Locale = (typeof supportedLocales)[number];\nexport const localeLabels: Record<Locale, string> = ${JSON.stringify({ en: "English", vi: "Tiếng Việt", ja: "日本語" }, null, 2)};\nexport const translations: Record<Locale, Record<string, string>> = ${JSON.stringify(translations, null, 2)};\nexport type TranslationKey = keyof (typeof translations)["en"];\n`;
await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, output, "utf8");
process.stdout.write(`Generated ${outputPath}\n`);
