import { useCallback, useEffect, useMemo, useState } from "react";
import { IconAlertTriangle, IconChartBar, IconCheck, IconRefresh } from "@tabler/icons-react";

import type { Bill, BillAnalysis, BillReminders } from "@/api/contracts";
import { api } from "@/api/client";
import { Button, EmptyState, LoadingPanel, Notice, PageHeading } from "@/components/ui";
import { formatDate, formatMoney } from "@/lib/format";
import { useI18n } from "@/lib/i18n";

export function BillsView(): React.ReactElement {
  const { t } = useI18n();
  const [bills, setBills] = useState<Bill[]>([]); const [reminders, setReminders] = useState<BillReminders | null>(null); const [analysis, setAnalysis] = useState<BillAnalysis | null>(null); const [actor, setActor] = useState("local-user"); const [selectedBill, setSelectedBill] = useState(""); const [selectedIssuer, setSelectedIssuer] = useState(""); const [daysAhead, setDaysAhead] = useState(14); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [nextBills, nextReminders] = await Promise.all([api.bills(), api.billReminders(daysAhead)]); setBills(nextBills); setReminders(nextReminders); setSelectedBill((current) => current || nextBills.find((bill) => bill.payment_status !== "paid")?.id || ""); setSelectedIssuer((current) => current || nextBills[0]?.issuer_id || ""); } catch (reason) { setError(reason instanceof Error ? reason.message : t("bills.unavailable", { detail: "" })); } finally { setLoading(false); } }, [daysAhead, t]);
  useEffect(() => { void load(); }, [load]);
  const issuers = useMemo(() => Array.from(new Map(bills.map((bill) => [bill.issuer_id, bill.issuer])).entries()), [bills]);
  const pay = async (): Promise<void> => { if (!selectedBill || !actor.trim()) { setError(t("bills.actor_required")); return; } setWorking(true); try { const paid = await api.markBillPaid(selectedBill, actor.trim()); setNotice(t("bills.marked_paid", { bill_id: paid.bill_id })); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : t("bills.mark_failed", { detail: "unknown error" })); } finally { setWorking(false); } };
  const loadAnalysis = async (): Promise<void> => { if (!selectedIssuer) return; setWorking(true); try { setAnalysis(await api.billAnalysis(selectedIssuer, 13, 12)); } catch (reason) { setError(reason instanceof Error ? reason.message : t("bills.analysis_unavailable", { detail: "" })); } finally { setWorking(false); } };
  return <div className="page-stack"><PageHeading title={t("page.bills.title")} copy={t("page.bills.copy")} action={<Button className="button-secondary" onClick={() => void load()}><IconRefresh size={18} />{t("action.reload")}</Button>} />
    {notice ? <Notice tone="success" onDismiss={() => setNotice(null)}>{notice}</Notice> : null}{error ? <Notice tone="error" onDismiss={() => setError(null)}>{error}</Notice> : null}{loading ? <LoadingPanel label={t("loading.bill_records")} /> : null}{!loading && !bills.length ? <EmptyState title={t("bills.empty")} copy={t("bills.projections_pending")} /> : null}
    {bills.length ? <><section className="bill-grid"><div className="data-table-wrap"><table><thead><tr><th>{t("column.issuer")}</th><th>{t("column.billing_period")}</th><th>{t("column.amount")}</th><th>{t("column.due_date")}</th><th>{t("column.payment_status")}</th></tr></thead><tbody>{bills.map((bill) => <tr key={bill.id}><td>{bill.issuer}</td><td>{formatDate(bill.billing_period)}</td><td>{formatMoney(bill.amount)}</td><td>{formatDate(bill.due_date)}</td><td><span className={bill.payment_status === "paid" ? "status-chip is-paid" : "status-chip"}>{bill.payment_status}</span></td></tr>)}</tbody></table></div><aside className="payment-panel"><span className="eyebrow">{t("bills.payment")}</span><h2>{t("bills.mark_paid")}</h2><label>{t("bills.unpaid_bill")}<select value={selectedBill} onChange={(event) => setSelectedBill(event.target.value)}>{bills.filter((bill) => bill.payment_status !== "paid").map((bill) => <option key={bill.id} value={bill.id}>{bill.issuer} · {formatMoney(bill.amount)} · {formatDate(bill.due_date)}</option>)}</select></label><label>{t("bills.payment_actor")}<input value={actor} onChange={(event) => setActor(event.target.value)} /></label><Button className="button-primary" onClick={() => void pay()} disabled={working || !selectedBill}><IconCheck size={18} />{t("bills.mark_paid")}</Button></aside></section>
      <section className="reminder-section"><div className="section-title"><div><span className="eyebrow">{t("bills.calendar")}</span><h2>{t("bills.due_reminders")}</h2></div><label>{t("bills.days_ahead")}<input type="number" min="0" max="365" value={daysAhead} onChange={(event) => setDaysAhead(Number(event.target.value))} onBlur={() => void load()} /></label></div><div className="reminder-columns"><ReminderList title={t("bills.overdue_count", { count: reminders?.overdue.length ?? 0 })} tone="overdue" items={reminders?.overdue ?? []} emptyCopy={t("bills.no_matching_reminders")} /><ReminderList title={t("bills.due_within", { count: reminders?.upcoming.length ?? 0, days: daysAhead })} tone="upcoming" items={reminders?.upcoming ?? []} emptyCopy={t("bills.no_matching_reminders")} /></div></section>
      <section className="analysis-section"><div className="section-title"><div><span className="eyebrow">{t("bills.issuer_history")}</span><h2>{t("bills.issuer_analysis")}</h2></div><div className="analysis-actions"><select aria-label={t("bills.issuer")} value={selectedIssuer} onChange={(event) => setSelectedIssuer(event.target.value)}>{issuers.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><Button className="button-secondary" onClick={() => void loadAnalysis()} disabled={working}><IconChartBar size={18} />{t("bills.load_analysis")}</Button></div></div>{analysis ? <div className="analysis-results"><ResultTable title={t("bills.comparisons")} values={analysis.comparisons} emptyCopy={t("bills.no_local_signals")} /><ResultTable title={t("bills.anomalies")} values={analysis.anomalies} emptyCopy={t("bills.no_local_signals")} /></div> : <p className="muted-copy">{t("bills.select_issuer")}</p>}</section></> : null}
  </div>;
}

function ReminderList({ title, tone, items, emptyCopy }: { title: string; tone: "overdue" | "upcoming"; items: Record<string, unknown>[]; emptyCopy: string }): React.ReactElement {
  return <article className={`reminder-list is-${tone}`}><h3>{tone === "overdue" ? <IconAlertTriangle size={19} /> : <IconRefresh size={19} />}{title}</h3>{items.length ? <ul>{items.map((item, index) => <li key={`${String(item.id ?? item.issuer ?? "reminder")}-${index}`}><strong>{String(item.issuer ?? item.id ?? "")}</strong><span>{formatDate(typeof item.due_date === "string" ? item.due_date : undefined)}</span></li>)}</ul> : <p>{emptyCopy}</p>}</article>;
}

function ResultTable({ title, values, emptyCopy }: { title: string; values: Record<string, unknown>[]; emptyCopy: string }): React.ReactElement {
  return <article className="result-table"><h3>{title}</h3>{values.length ? <pre>{JSON.stringify(values, null, 2)}</pre> : <p>{emptyCopy}</p>}</article>;
}

export default BillsView;
