"""Safely normalize image uploads before sending them to an OCR engine."""

from __future__ import annotations

import hashlib
import io
import warnings

from PIL import Image, ImageOps, UnidentifiedImageError

from clerksan.ingest.filetype import FileType
from clerksan.ingest.limits import IngestLimits, ResourceLimitExceeded, check_image_pixels
from clerksan.ingest.normalized import (
    DocMetadata,
    ExtractedImage,
    NormalizedDocument,
    canonical_json,
)
from clerksan.ingest.parser_artifacts import (
    PNG_MIME,
    AdapterRunResult,
    ArtifactRole,
    GeneratedArtifact,
)
from clerksan.ingest.parser_runner import AdapterContext, ReadOnlySource
from clerksan.llm.ocr import OcrEngine

from .source_io import read_bounded_source


class ImageAdapter:
    """Normalize supported raster uploads for structural parsing or parent OCR."""

    supported_types: tuple[FileType, ...] = (
        FileType.JPEG,
        FileType.PNG,
        FileType.WEBP,
        FileType.BMP,
        FileType.GIF,
        FileType.TIFF,
    )

    def __init__(self, ocr: OcrEngine, *, limits: IngestLimits | None = None) -> None:
        self.ocr = ocr
        self.limits = limits or IngestLimits()

    def normalize(self, source: ReadOnlySource, context: AdapterContext) -> NormalizedDocument:
        """Return structural metadata for direct adapter callers.

        Sidecar callers use :meth:`normalize_with_artifacts`; this compatibility
        seam intentionally does not make generated bytes look like host paths.
        """

        return self.normalize_with_artifacts(source, context).normalized

    def normalize_with_artifacts(
        self, source: ReadOnlySource, context: AdapterContext
    ) -> AdapterRunResult:
        """Decode one image into an upright RGB PNG without invoking OCR."""

        detected_type = _context_file_type(context)
        if detected_type not in self.supported_types:
            raise ValueError(f"image adapter cannot handle {detected_type.value!r}")
        raw = read_bounded_source(source, self.limits)
        image = _decode_and_normalize(raw, self.limits, expected_type=detected_type)
        try:
            width, height = image.size
            sanitized = _as_png(image)
        finally:
            image.close()
        if len(sanitized) > self.limits.max_normalized_output_bytes:
            raise ResourceLimitExceeded(
                "max_normalized_output_bytes",
                self.limits.max_normalized_output_bytes,
                len(sanitized),
            )
        digest = hashlib.sha256(sanitized).hexdigest()
        artifact = GeneratedArtifact(
            role=ArtifactRole.SANITIZED_IMAGE,
            media_type=PNG_MIME,
            data=sanitized,
            page_number=1,
            width=width,
            height=height,
            source_location="image:1",
            ocr_required=True,
        )
        normalized = NormalizedDocument(
            markdown_body="",
            metadata=DocMetadata(
                filename=source.filename,
                detected_type=detected_type,
                sha256=source.source_sha256,
                family="image",
                canonical_mime=_context_text(context, "canonical_mime"),
                page_provenance=["ocr_required"],
                extra={
                    "ocr_required": True,
                    "ocr_required_pages": [1],
                    "sanitized_artifact_sha256": digest,
                    "sanitized_image_format": "png",
                    "structural_decode": "pillow",
                },
            ),
            images=[
                ExtractedImage(
                    sha256=digest,
                    content_path="artifact:sanitized-image:1",
                    width=width,
                    height=height,
                    source_location="image:1",
                )
            ],
            embeddable=False,
        )
        aggregate_output = len(sanitized) + len(
            canonical_json(normalized.model_dump(mode="json")).encode("utf-8")
        )
        if aggregate_output > self.limits.max_normalized_output_bytes:
            raise ResourceLimitExceeded(
                "max_normalized_output_bytes",
                self.limits.max_normalized_output_bytes,
                aggregate_output,
            )
        return AdapterRunResult(normalized=normalized, artifacts=(artifact,))

    async def adapt(self, raw: bytes, meta: DocMetadata) -> NormalizedDocument:
        """Decode a bounded image, normalize its orientation, then run OCR.

        The adapter deliberately does not persist a second file.  The ingest pipeline
        owns immutable storage, while this seam uses the original path supplied in
        metadata or a deterministic content-addressed reference.
        """

        if meta.detected_type not in self.supported_types:
            raise ValueError(f"image adapter cannot handle {meta.detected_type.value!r}")

        image = _decode_and_normalize(raw, self.limits)
        try:
            image_bytes = _as_png(image)
            ocr_result = await self.ocr.ocr(image_bytes)
            width, height = image.size
        finally:
            image.close()

        digest = hashlib.sha256(raw).hexdigest()
        extra = dict(meta.extra)
        extra.update(
            {
                "ocr_engine": self.ocr.name,
                "ocr_confidence_is_self_reported": ocr_result.confidence_is_self_reported,
                "normalized_image_format": "png",
            }
        )
        normalized_meta = meta.model_copy(update={"page_provenance": ["ocr"], "extra": extra})
        return NormalizedDocument(
            markdown_body=ocr_result.text.strip(),
            metadata=normalized_meta,
            images=[
                ExtractedImage(
                    sha256=digest,
                    content_path=_original_content_path(meta, digest),
                    width=width,
                    height=height,
                    source_location="image:1",
                )
            ],
        )


def _decode_and_normalize(
    raw: bytes,
    limits: IngestLimits,
    *,
    expected_type: FileType | None = None,
) -> Image.Image:
    """Verify image bytes and enforce header dimensions before full decoding."""

    try:
        with warnings.catch_warnings():
            warnings.simplefilter("error", Image.DecompressionBombWarning)
            with Image.open(io.BytesIO(raw)) as probe:
                _validate_detected_format(probe.format, expected_type)
                check_image_pixels(*probe.size, limits)
                frame_count = int(getattr(probe, "n_frames", 1))
                if frame_count > limits.max_image_frames:
                    raise ResourceLimitExceeded(
                        "max_image_frames", limits.max_image_frames, frame_count
                    )
                probe.verify()

        with warnings.catch_warnings():
            warnings.simplefilter("error", Image.DecompressionBombWarning)
            with Image.open(io.BytesIO(raw)) as source:
                _validate_detected_format(source.format, expected_type)
                normalized = ImageOps.exif_transpose(source).convert("RGB")
                normalized.load()
                return normalized
    except (Image.DecompressionBombError, Image.DecompressionBombWarning) as error:
        raise ValueError("image exceeds Pillow safety limits") from error
    except (OSError, UnidentifiedImageError) as error:
        raise ValueError("invalid or incomplete image upload") from error


def _as_png(image: Image.Image) -> bytes:
    """Give every OCR implementation the same upright, RGB byte representation."""

    output = io.BytesIO()
    image.info.clear()
    image.save(output, format="PNG")
    return output.getvalue()


def _validate_detected_format(pillow_format: str | None, expected_type: FileType | None) -> None:
    if expected_type is None:
        return
    actual = {
        "JPEG": FileType.JPEG,
        "PNG": FileType.PNG,
        "WEBP": FileType.WEBP,
        "BMP": FileType.BMP,
        "GIF": FileType.GIF,
        "TIFF": FileType.TIFF,
    }.get(pillow_format or "")
    if actual is not expected_type:
        raise ValueError("decoded image format does not match structural detection")


def _original_content_path(meta: DocMetadata, digest: str) -> str:
    """Use a persisted original path when supplied, otherwise a stable reference."""

    supplied = meta.extra.get("content_path")
    if supplied is not None:
        if not isinstance(supplied, str) or not supplied:
            raise ValueError("metadata.extra.content_path must be a non-empty string")
        return supplied
    return f"sha256/{digest}"


def _context_file_type(context: AdapterContext) -> FileType:
    try:
        return FileType(context.metadata.get("detected_type", ""))
    except ValueError as error:
        raise ValueError("image adapter context requires a detected type") from error


def _context_text(context: AdapterContext, key: str) -> str | None:
    value = context.metadata.get(key)
    return value if isinstance(value, str) else None
